services:
  - type: web
    name: car-dealership
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"